import React, { useState, useEffect } from 'react';
import { dashboardAPI } from '../api/client';

export default function XlsxPreview({ filename, folder, headerRows = 1, indexCols = 0, centerHeaders = false, rotateFirstIndex = false, rotateLowestHeaders = false }) {
  const [htmlContent, setHtmlContent] = useState(null);
  const [error, setError] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!filename) return;

    const fetchExcel = async () => {
      try {
        setLoading(true);
        setError(null);
        
        const response = await dashboardAPI.previewExcel(filename, folder, headerRows, indexCols, centerHeaders);
        setHtmlContent(response.html);
      } catch (err) {
        console.error(err);
        setError(err.response?.data?.detail || err.message || 'Errore nel caricamento del file Excel');
      } finally {
        setLoading(false);
      }
    };

    fetchExcel();
  }, [filename, folder, headerRows, indexCols, centerHeaders]);

  if (loading) return <div className="p-4 text-center text-gray-500 animate-pulse">Caricamento anteprima Excel in corso...</div>;
  if (error) return <div className="p-4 text-center text-red-500 bg-red-50 rounded">Nessuna anteprima disponibile ({error})</div>;
  if (!htmlContent) return <div className="p-4 text-center text-gray-500">Il foglio Excel è vuoto.</div>;

  return (
    <div className="mt-6">
      <h3 className="text-lg font-semibold text-gray-700 mb-2">Anteprima Dati (Prime 10 righe)</h3>
      <div className="overflow-x-auto border border-gray-200 rounded-lg shadow-sm bg-white p-1">
        {/* We use a style tag for complex CSS and to make sure it hits the right line (the second to last, because the last one has the index name) */}
        {rotateLowestHeaders && (
          <style>{`
            .rotate-lowest-headers table thead tr:nth-last-child(2) th {
              writing-mode: vertical-rl;
              transform: rotate(180deg);
              text-align: center;
              vertical-align: middle;
              height: 7rem;
              width: 2.5rem;
            }
          `}</style>
        )}
        {/* Styles for the table generated by pandas (which uses the standard HTML tags table, thead, tbody, th, td, tr) */}
        <div 
          className={`xlsx-preview-container [&>table]:w-full [&>table]:text-sm [&>table]:text-left [&>table>thead]:bg-gray-100 [&>table>thead]:border-b [&>table_th]:p-3 [&>table_th]:text-gray-800 [&>table_th]:font-semibold [&>table_tr]:border-b [&>table>tbody>tr:hover]:bg-gray-50 [&>table_td]:p-3 [&>table_td]:text-gray-600 [&>table_th]:border-r [&>table_th:last-child]:border-r-0 [&>table_td]:border-r [&>table_td:last-child]:border-r-0
            ${centerHeaders ? '[&>table>thead>tr>th]:text-center [&>table>tbody>tr>th]:text-center [&>table_td]:text-center' : ''}
            ${rotateFirstIndex ? '[&>table>tbody>tr>th[rowspan]]:[writing-mode:vertical-rl] [&>table>tbody>tr>th[rowspan]]:rotate-180 [&>table>tbody>tr>th[rowspan]]:text-center [&>table>tbody>tr>th[rowspan]]:align-middle [&>table>tbody>tr>th[rowspan]]:w-10' : ''}
            ${rotateLowestHeaders ? 'rotate-lowest-headers' : ''}
          `}
          dangerouslySetInnerHTML={{ __html: htmlContent }} 
        />
      </div>
    </div>
  );
}
